<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container353Xb1W\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container353Xb1W/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container353Xb1W.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container353Xb1W\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container353Xb1W\App_KernelDevDebugContainer([
    'container.build_hash' => '353Xb1W',
    'container.build_id' => '99c767c3',
    'container.build_time' => 1586958893,
], __DIR__.\DIRECTORY_SEPARATOR.'Container353Xb1W');
