<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'GetGenre' => [['id'], ['_controller' => 'App\\Controller\\GenreController::getGenre'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/genre']], [], []],
    'GetMovie' => [['id'], ['_controller' => 'App\\Controller\\MovieController::getMovie'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/movie']], [], []],
    'GetPlace' => [['id'], ['_controller' => 'App\\Controller\\PlaceController::getPlace'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/place']], [], []],
    'PostRegistration' => [[], ['_controller' => 'App\\Controller\\RegistrationController::postRegistration'], ['_method' => 'POST'], [['text', '/registration']], [], []],
    'GetActor' => [['id'], ['_controller' => 'App\\Controller\\ActorController::getActor'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/actor']], [], []],
    'PostActorInMovie' => [[], ['_controller' => 'App\\Controller\\ActorController::postActorInMovie'], ['_method' => 'POST'], [['text', '/actorInMovie']], [], []],
    'PostAuth' => [[], ['_controller' => 'App\\Controller\\AuthController::postAuth'], ['_method' => 'POST'], [['text', '/auth']], [], []],
];
